apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/instance: image-registry-certificates-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: multiarch-manager-operator
    app.kubernetes.io/part-of: multiarch-manager-operator
    app.kubernetes.io/managed-by: kustomize
  name: image-registry-certificates-rolebinding
  namespace: openshift-image-registry
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: image-registry-certificates-role
subjects:
  - kind: ServiceAccount
    name: podplacement-controller
    namespace: system
