---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: podplacement-controller-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: multiarch-manager-operator
    app.kubernetes.io/part-of: multiarch-manager-operator
    app.kubernetes.io/managed-by: kustomize
  name: podplacement-controller-role
rules:
  - apiGroups:
      - config.openshift.io
    resources:
      - images
      - imagetagmirrorsets
      - imagedigestmirrorsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - operator.openshift.io
    resources:
      - imagecontentsourcepolicies
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - use