---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/instance: podplacement-leader-election-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: multiarch-manager-operator
    app.kubernetes.io/part-of: multiarch-manager-operator
    app.kubernetes.io/managed-by: kustomize
  name: podplacement-leader-election-rolebinding
  namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-election-role
subjects:
  - kind: ServiceAccount
    name: podplacement-controller
