resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: quay.io/pbastide_rh/openshift-demo
  newTag: multiarch-manager-operator-1.0.0
commonAnnotations:
  multiarch.openshift.io/image: quay.io/pbastide_rh/openshift-demo:multiarch-manager-operator-1.0.0
