# permissions for end users to view podplacementconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: podplacementconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: multiarch-manager-operator
    app.kubernetes.io/part-of: multiarch-manager-operator
    app.kubernetes.io/managed-by: kustomize
  name: podplacementconfig-viewer-role
rules:
- apiGroups:
  - multiarch.openshift.io
  resources:
  - podplacementconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - multiarch.openshift.io
  resources:
  - podplacementconfigs/status
  verbs:
  - get
